version: "3.9"
name: webdoc

services:
  web:
    volumes:
     - ./templates:/etc/nginx/templates #вольюм обкашляем еще
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
     - "8080:80"    #порты
    environment:
     - NGINX_HOST=foobar.com  #хост обкашляем
     - NGINX_PORT=80          #порт тоже потом можно пересмотреть

  app:
    restart: always
    cpu_count: 1    #потом можно будет пересмотреть
    shm_size: 128mb   #потом можно будет пересмотреть
    depends_on:
      web:
        condition: service_started    #условие для запуска, чтобы сначала поднялся nginx
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "9999:9999"